- name: Launch LMOD v{{ NSP_LMOD_version }} Install
  ansible.builtin.include_tasks:
    file: install.yaml
  when: not [NSP_install_root, 'lmod', NSP_LMOD_version] | path_join is directory
  tags:
    - lmod
    - installation

- name: Create LMOD Cache Directory
  ansible.builtin.file:
    path: "{{ [NSP_install_root, 'lmod/cache/cacheDir'] | path_join }}"
    state: directory
    owner: "{{ NSP_user }}"
    group: "{{ NSP_group }}"
    mode: "{{ NSP_executable_permissions }}"
  tags:
    - lmod
    - configuration

- name: Create LMOD Default Module Paths File
  ansible.builtin.template:
    src: modulepath.default.j2
    dest: "{{ [NSP_install_root, 'lmod/etc/modulepath.default'] | path_join }}"
    owner: "{{ NSP_user }}"
    group: "{{ NSP_group }}"
    mode: "{{ NSP_file_permissions }}"
  tags:
    - lmod
    - configuration

- name: Insert LMOD Init profile Configuration
  ansible.builtin.blockinfile:
    block: |
      type module > /dev/null 2>&1
      if [ "$?" -eq 0 ]; then
          clearLmod -q > /dev/null 2>&1
          unset LMOD_MODULEPATH_INIT
      fi

      export LMOD_SYSTEM_NAME={{ NSP_system_name }}
      export LMOD_SYSTEM_DEFAULT_MODULES=DefApps
      export LMOD_PACKAGE_PATH={{ [NSP_install_root, 'lmod/hooks'] | path_join }}
      export LMOD_AVAIL_STYLE=nsp-pretty:system
      export LMOD_MODULERCFILE={{ [NSP_install_root, 'lmod/etc/rc.lua'] | path_join }}
      export LMOD_ADMIN_FILE={{ [NSP_install_root, 'lmod/etc/admin.list'] | path_join }}
      export LMOD_RC={{ [NSP_install_root, 'lmod/etc/lmodrc.lua'] | path_join }}

      source {{ [NSP_install_root, 'lmod/lmod/init/profile'] | path_join }}
      module --initial_load --no_redirect restore
    path: "{{ [NSP_install_root, 'init', 'profile'] | path_join }}"
    owner: "{{ NSP_user }}"
    group: "{{ NSP_group }}"
    mode: "{{ NSP_file_permissions }}"
    marker: "# {mark} LMOD MANAGED"
    append_newline: true
    prepend_newline: true
  tags:
    - lmod
    - configuration

- name: Insert LMOD Init cshrc Configuration
  ansible.builtin.blockinfile:
    block: |
      type module >&/dev/null
      if ($status == 0) then
          clearLmod -q >&/dev/null
          unset LMOD_MODULEPATH_INIT
      endif

      setenv LMOD_SYSTEM_NAME {{ NSP_system_name }}
      setenv LMOD_SYSTEM_DEFAULT_MODULES DefApps
      setenv LMOD_PACKAGE_PATH {{ [NSP_install_root, 'lmod/hooks'] | path_join }}
      setenv LMOD_AVAIL_STYLE nsp-pretty:system
      setenv LMOD_MODULERCFILE {{ [NSP_install_root, 'lmod/etc/rc.lua'] | path_join }}
      setenv LMOD_ADMIN_FILE {{ [NSP_install_root, 'lmod/etc/admin.list'] | path_join }}
      setenv LMOD_RC {{ [NSP_install_root, 'lmod/etc/lmodrc.lua'] | path_join }}

      source {{ [NSP_install_root, 'lmod/lmod/init/cshrc'] | path_join }}
      module --initial_load --no_redirect restore
    path: "{{ [NSP_install_root, 'init', 'cshrc'] | path_join }}"
    owner: "{{ NSP_user }}"
    group: "{{ NSP_group }}"
    mode: "{{ NSP_file_permissions }}"
    marker: "# {mark} LMOD MANAGED"
    append_newline: true
    prepend_newline: true
  tags:
    - lmod
    - configuration
