- name: Check for LMOD v{{ NSP_LMOD_version }} Install
  ansible.builtin.stat:
    path: "{{ [NSP_LMOD_install_root, NSP_LMOD_version] | path_join }}"
  register: lmod_status
  tags:
    - lmod

- name: Launch LMOD v{{ NSP_LMOD_version }} Install
  ansible.builtin.include_tasks:
    file: install.yaml
  when: not lmod_status.stat.exists
  tags:
    - lmod

- name: Create LMOD Cache Directory
  ansible.builtin.file:
    path: "{{ [NSP_LMOD_install_root, 'cache/cacheDir'] | path_join }}"
    state: directory
    owner: "{{ NSP_user }}"
    group: "{{ NSP_group }}"
    mode: "{{ NSP_executable_permissions }}"
  tags:
    - lmod

- name: Create LMOD Default Module Paths File
  ansible.builtin.template:
    src: modulepath.default.j2
    dest: "{{ [NSP_LMOD_install_root, 'etc/modulepath.default'] | path_join }}"
    owner: "{{ NSP_user }}"
    group: "{{ NSP_group }}"
    mode: "{{ NSP_file_permissions }}"
  tags:
    - lmod
