- name: Create Init Directory
  ansible.builtin.file:
    path: "{{ [NSP_install_root, 'init'] | path_join }}"
    state: directory
    owner: "{{ NSP_user }}"
    group: "{{ NSP_group }}"
    mode: "{{ NSP_executable_permissions }}"
  tags:
    - init

- name: Generate profile
  ansible.builtin.template:
    src: profile.j2
    dest: "{{ [NSP_install_root, 'init', 'profile'] | path_join }}"
    owner: "{{ NSP_user }}"
    group: "{{ NSP_group }}"
    mode: "{{ NSP_file_permissions }}"
  tags:
    - init

- name: Generate cshrc
  ansible.builtin.template:
    src: cshrc.j2
    dest: "{{ [NSP_install_root, 'init', 'cshrc'] | path_join }}"
    owner: "{{ NSP_user }}"
    group: "{{ NSP_group }}"
    mode: "{{ NSP_file_permissions }}"
  tags:
    - init
